name: Hello-World and Cache Pipeline
on: [push]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, World!!

    - name: Send email
      uses: dawidd6/action-send-mail@v3.2.0
      with:
        server_address: smtp.gmail.com
        server_port: 465
      # Authenticate as this user to SMTP server
        username: ${{secrets.MAIL_USERNAME}}
      # Authenticate with this password to SMTP server
        password: ${{secrets.MAIL_PASSWORD}}
      # Subject of mail message
        subject: GH Actions Mail Result
      # Recipients mail addresses (separated with comma)
        to: francisco_ortiz1@yahoo.com
      # Full name of mail sender (might be with an email address specified in <>)
        from: Francisco
      # Whether this connection use TLS (default is true if server_port is 465)
        secure: true
      # Body of mail message (might be a filename prefixed with file:// to read from)
        body: Build job of ${{github.repository}} completed successfully!
      # HTML body of mail message (might be a filename prefixed with file:// to read from)
        html_body: file://README.html
      # Carbon copy recipients (separated with comma)
        cc: francisco_ortiz1@yahoo.com
      # Blind carbon copy recipients (separated with comma)
        bcc: francisco_ortiz1@yahoo.com
      # An email address that will appear on the Reply-To field
        reply_to: francisco_ortiz1@yahoo.com
      # Allow unsigned/invalid certificates
        ignore_cert: true
      # Convert body from Markdown to HTML (set content_type input as text/html too)
        convert_markdown: true
      # Files that will be added to mail message attachments (separated with comma)
       # attachments: # optional
      

