name: Hello-World and Cache Pipeline
on:
  schedule:
  - cron: "0 2 * * 1-5"
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, World!!
      

